### ISSUE TITLE
Navbar - html/css/js

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Login#10]
brand Name - Xf
login 
signUp
About
-NOTE
- create overview.html(inside public) and overview.css(inside public/css)

**Comment by manthankhawse** [comment]
hello @manzil-infinity180 I would like to work on this issue can you please assign it to me

**Comment by manthankhawse** [comment]
just a question 
this is what is visible currently
![image](https://github.com/manzil-infinity180/Login/assets/86763361/603525d3-d5fa-4a46-83e1-9205e3a866b0)
so I have to create a navbar above the login form . If yes , the navbar should have the company name , link to login route,signup route and about page . Is that correct?

**Comment by manthankhawse** [comment]
and it would be very helpful if you can specify what content is to be included in about page

**Comment by manzil-infinity180** [comment]
> just a question this is what is visible currently ![image](https://user-images.githubusercontent.com/86763361/271893005-603525d3-d5fa-4a46-83e1-9205e3a866b0.png) so I have to create a navbar above the login form . If yes , the navbar should have the company name , link to login route,signup route and about page . Is that correct?


I know it looks weird because i have'nt created overview page yet, you are correct

**Comment by manthankhawse** [comment]
so how should I proceed , there isnt any view for signup and about either

**Comment by manzil-infinity180** [comment]
> so how should I proceed , there isnt any view for signup and about either

<img width="1467" alt="Screenshot 2023-10-02 at 12 02 45 PM" src="https://github.com/manzil-infinity180/Login/assets/119070053/d49bc58d-b6aa-44a4-b7c9-ba4408c39377">

ALL tour ===> Xf
In about - fill the random quotes i will update it later

**Comment by manthankhawse** [comment]
And what about signup

**Comment by manzil-infinity180** [comment]
> And what about signup

same as login but don't put any link to it

**Comment by manthankhawse** [comment]
ok

**Comment by manthankhawse** [comment]
instead of overview.html , i created navbar in index.html and about.html only 
so this is what i have come up with 
![image](https://github.com/manzil-infinity180/Login/assets/86763361/de5487a6-70b5-46f0-9e13-34c8b6afb81e)
login takes you to "/"
signup has no link
About takes you to about.html
![image](https://github.com/manzil-infinity180/Login/assets/86763361/24d588bb-7e64-4a82-b82a-21f2436398f2)

Anything else I should add or anything that i have got wrong?

**Comment by manzil-infinity180** [comment]
> instead of overview.html , i created navbar in index.html and about.html only so this is what i have come up with ![image](https://user-images.githubusercontent.com/86763361/271904592-de5487a6-70b5-46f0-9e13-34c8b6afb81e.png) login takes you to "/" signup has no link About takes you to about.html ![image](https://user-images.githubusercontent.com/86763361/271905087-24d588bb-7e64-4a82-b82a-21f2436398f2.png)
> 
> Anything else I should add or anything that i have got wrong?

just one thing to change is to change the background color to back of the navbar section
<img width="1467" alt="Screenshot 2023-10-02 at 12 02 45 PM" src="https://github.com/manzil-infinity180/Login/assets/119070053/46cb897f-9e11-4b21-bf1b-3ae340063fd0">

**Comment by manthankhawse** [comment]
![image](https://github.com/manzil-infinity180/Login/assets/86763361/b2493af5-2e6f-4bb1-837c-42605041c315)
is it okay?

**Comment by manzil-infinity180** [comment]
It's look good 👌

**Comment by manthankhawse** [comment]
ok then im creating a pull request
