### ISSUE TITLE
Footer UI Section - html /css/js

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Login#11]
Some Links (Take help of Rahul-Portfolio Project)(https://manzil-infinity180.github.io/Rahul-portfolio.io/)

```

<footer class="white-section" id="social-links">
    <div class="container-fluid">

        <a href="https://www.linkedin.com/in/rahul-vishwakarma-553874256/"><i class="fa-brands fa-linkedin fa-2x footer-icon"></i></a>
        <a href="https://www.instagram.com/manzil.infinity180/"><i class="fa-brands fa-instagram fa-2x footer-icon"></i></a>
        <a href="https://github.com/manzil-infinity180"><i class="fa-brands fa-github fa-2x footer-icon"></i></a>
        <a href="https://www.hackerrank.com/rahulvs2809"><i class="fa-brands fa-hackerrank fa-2x footer-icon"></i></a>
        <a href="mailto:rahulvs2809@gmail.com"> <i class="fa-solid fa-envelope fa-2x footer-icon"></i></a>
    <p class="copyright">© Rahul Vishwakarma</p>
  </div>
  </footer>

```

**Comment by Abhishekvermaa** [comment]
Hii manzil !!
where can i see your website?

**Comment by manzil-infinity180** [comment]
> Hii manzil !! where can i see your website?
its not a website - its all backend stuff 
if you want to add footer then add inside `public/index.html`

**Comment by manzil-infinity180** [comment]
> Hii manzil !! where can i see your website?

its not a website - its all backend stuff 
if you want to add footer then add inside `public/index.html`
@Abhishekvermaa

**Comment by bbhupen** [comment]
Hi @manzil-infinity180 can I work on this issue?

**Comment by manzil-infinity180** [comment]
> Hi @manzil-infinity180 can I work on this issue?

go for it

**Comment by bbhupen** [comment]
Hey @manzil-infinity180 just raised a PR regarding this. Please review
