### ISSUE TITLE
Add issue and star count dynamically using (shields.io) inside Readme file

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Login#13]

**Comment by khushpreetsinghb** [comment]
I am new to open source, I can do this. Can you please assign this to me ?

**Comment by khushpreetsinghb** [comment]
Thank you for assigning me this issue. Can you please tell me that where do I add these inside the Readme file ?

**Comment by manzil-infinity180** [comment]
> Thank you for assigning me this issue. Can you please tell me that we do I add these ?

search here you can find it how to create
https://shields.io/

**Comment by khushpreetsinghb** [comment]
I want to know that where I add these badges inside the Readme file .

**Comment by manzil-infinity180** [comment]
> I want to know that where I add these badges inside the Readme file .

below the Login text

**Comment by khushpreetsinghb** [comment]
Before Language/Tools/Other ?

**Comment by manzil-infinity180** [comment]
Yeah

**Comment by khushpreetsinghb** [comment]
Okay I am doing this.

**Comment by khushpreetsinghb** [comment]
Thank you

**Comment by khushpreetsinghb** [comment]
Can you please add the label hacktoberfest-accepted to this.

**Comment by manzil-infinity180** [comment]
> Can you please add the label hacktoberfest-accepted to this.

I think no need of it I already added to repo

**Comment by khushpreetsinghb** [comment]
Okay
