### ISSUE TITLE
Update ReadMe file

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Login#15]
[Language/Tools/Other](https://github.com/manzil-infinity180/Login#languagetoolsother)
HTML/CSS/JS
NodeJs
ExpressJs
MongodB
Mongoose
PugJs
Axios
PostManAPI

 

<img width="818" alt="Screenshot 2023-10-02 at 11 35 36 AM" src="https://github.com/manzil-infinity180/Login/assets/119070053/7ed8877e-acb0-430c-9e43-f317c7fa5224">

**Comment by joshijoe05** [comment]
Please elaborate the issue, I would like to work on this

**Comment by manzil-infinity180** [comment]
> Please elaborate the issue, I would like to work on this

update the readme file , like the image i provide something like this - you can use ([shield.io](https://shields.io/badges)) to create this or check my profile readme file you can get the idea how to create

**Comment by manzil-infinity180** [comment]
> Please elaborate the issue, I would like to work on this
<img width="1680" alt="Screenshot 2023-10-02 at 11 58 23 AM" src="https://github.com/manzil-infinity180/Login/assets/119070053/02ef2937-81de-414a-81c4-96ed58bc98e4">

<img width="1680" alt="Screenshot 2023-10-02 at 11 58 28 AM" src="https://github.com/manzil-infinity180/Login/assets/119070053/0ae4aefe-656e-4f35-b21c-15a019eee2ed">

ex- 
HTML5-008000 (008000 - color hash code)
for-the-badge (for style)

**Comment by the-amazing-atharva** [comment]
@manzil-infinity180 I would like to work on this issue for hacktoberfest
