### ISSUE TITLE
Overview Page (UI) - html / CSS 

### ISSUE THREAD

**Issue by manzil-infinity180** [manzil-infinity180/Login#9]
It contain 
- Buttton_NAME Button - on clicking the button head over to http://localhost:8080/Buttton_NAME(ex- http://localhost:8080/login)
buttons are - 
/login
/signup
/forgotPassword
/resetPassword
/GetUser
/GetAllUser
/GetDetail
NOTE-
- create overview.html(inside public) and overview.css(inside public/css)

**Comment by vamsi-spoidey7** [comment]
when the button is clicked it should head over to that specified page right?
i would like to work on this issue

**Comment by manzil-infinity180** [comment]
> when the button is clicked it should head over to that specified page right? i would like to work on this issue

Yeah , Go for it

**Comment by vamsi-spoidey7** [comment]
please usassign me. As frontend is not cup of my tea

**Comment by manzil-infinity180** [comment]
> please usassign me. As frontend is not cup of my tea

NO problem , i am just creating this all stuff for myself but if someone want to work then i am here to assign it

**Comment by avyuktsoni0731** [comment]
Hello @manzil-infinity180 ! I wanted to know more about this issue. We are supposed to only add the buttons, link it and add designing to it using CSS right? And can I also please get to know more about the format in which we are to develop the webpage?

Thanks : )

**Comment by manzil-infinity180** [comment]
> Hello @manzil-infinity180 ! I wanted to know more about this issue. We are supposed to only add the buttons, link it and add designing to it using CSS right? And can I also please get to know more about the format in which we are to develop the webpage?
> 
> Thanks : )

I want the page to be very simple , i will work on that later , mainly i focus to build the backend part more

**Comment by avyuktsoni0731** [comment]
@manzil-infinity180 okay got that!

I would love to work on this issue, it would be great if you assign it to me.
